[package]
name = "sol-green"
version = "0.1.0"
description = "Sol-Green环保奖励智能合约"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "sol_green"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
